I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 297, in script
    show peter_evil at Alright
  File "game/script.rpy", line 297, in <module>
    show peter_evil at Alright
NameError: name 'Alright' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 297, in script
    show peter_evil at Alright
  File "renpy/ast.py", line 1182, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1141, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "renpy/python.py", line 2142, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2135, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 297, in <module>
    show peter_evil at Alright
NameError: name 'Alright' is not defined

